### ISSUE TITLE
"Warning: Accessing PropTypes via the main React package is deprecated"

### ISSUE THREAD

**Issue by dbuezas** [leonardowf/react-simple-currency#13]
https://github.com/leonardowf/react-simple-currency/blob/master/lib/SimpleCurrencyInput.js#L157

/Users/...../node_modules/react/lib/lowPriorityWarning.js:40 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by dbuezas** [comment]
#14

**Comment by leonardowf** [comment]
Merged and released, thanks
