### ISSUE TITLE
Input Classname / Props

### ISSUE THREAD

**Issue by sergiokopplin** [leonardowf/react-simple-currency#2]
Hello, thank for the awesome component.

---

I want to add some classes to the input, how can i do that?
Or even a comum prop.

[Example](https://github.com/moroshko/react-autosuggest/blob/master/demo/src/components/App/components/Examples/components/Basic/Basic.js#L61).

**Comment by marlon407** [comment]
sergiokopplin, did you get any work around for this issue?

**Comment by sergiokopplin** [comment]
No. Sorry for the delay.
I used another solution.
